# Generated by Django 4.1.3 on 2023-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='avatar.svg', upload_to=''),
            preserve_default=False,
        ),
    ]
